version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9999:9999"
  app1:
    build:
      context: ./
      dockerfile: Dockerfile.python
    ports:
      - "8081:8081"
      - "9999:9999"
